language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./gradlew sonarqube build test javadoc asciidoc -Dsonar.organization=webauthn4j -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build/asciidoc/html5
    target-branch: gh-pages
    on:
      branch: master
      jdk: openjdk8
  - provider: script
    skip-cleanup: true
    script: ./gradlew bintrayUpload
    on:
      branch: master
      jdk: openjdk8
      tags: true

addons:
  sonarcloud:
    organization: "webauthn4j"
