language: java

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  # unshallow git repository
  - 'if [ "$TRAVIS_JDK_VERSION"  = "openjdk8" -a  "$SONAR_TOKEN" != "" ]; then git fetch --unshallow --quiet; fi'
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - 'if [ "$TRAVIS_JDK_VERSION" != "openjdk8" -o  "$SONAR_TOKEN"  = "" ]; then ./gradlew check javadoc asciidoc; fi'
  - 'if [ "$TRAVIS_JDK_VERSION"  = "openjdk8" -a  "$SONAR_TOKEN" != "" ]; then ./gradlew sonarqube check javadoc asciidoc -Dsonar.organization=webauthn4j -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi'
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build/asciidoc/html5
    target-branch: gh-pages
    on:
      branch: master
      jdk: openjdk8
  - provider: script
    skip-cleanup: true
    script: travis_wait 30 ./gradlew bintrayUpload
    on:
      jdk: openjdk8
      tags: true
  - provider: script
    skip-cleanup: true
    script: ./gradlew artifactoryPublish
    on:
      branch: master
      jdk: openjdk8

addons:
  sonarcloud:
    organization: "webauthn4j"
